[options]
; 数据库配置 (对应 docker-compose 中 db 服务的端口映射 5434->5432)
db_host = localhost
db_port = 5434
db_user = odoo
db_password = odoo

; 路径配置
addons_path = odoo/addons,custom_addons

; 服务端口
http_port = 8069

; 开发模式相关的日志和重载
dev = xml,reload
log_level = info
