[options]
; Database configuration
db_host = localhost
db_port = 5434
db_user = odoo
db_password = odoo

; Paths
addons_path = odoo/odoo/addons,odoo/addons,custom_addons

; Server port
http_port = 8069

; Dev mode and logging
dev = xml,reload
log_level = info
