# -*- coding: utf-8 -*-

from . import product_category
from . import diecut_brand
from . import product_diecut
from . import mold
from . import diecut_quote
from . import sample_order
from . import slitting
from . import requisition
from . import purchase_order
from . import res_partner
from . import stock_quant
from . import stock_move
from . import catalog_ops_log
from . import catalog_taxonomy
from . import catalog_ai
from . import catalog_ai_runtime_override
from . import catalog_ai_dual_runtime
from . import catalog_ai_openclaw_runtime
from . import catalog_ai_openclaw_vision_runtime
from . import catalog_ai_worker_runtime
from . import catalog_ai_generate_override
from . import catalog_spec
from . import catalog_param_ai_meta
from . import catalog_category_param
from . import catalog_series
from . import catalog_item
from . import catalog_ai_apply_fix
from . import catalog_ai_chatter_refine
