from . import my_material
from . import requisition
from . import slitting
from . import res_partner
from . import mold
from . import material
from . import my_material_inherit 
from . import diecut_quote
from . import sample_order
from . import purchase_order
from . import product_category
