# -*- coding: utf-8 -*-
{
    'name': '模切管理系统',
    'version': '1.0',
    'category': 'Manufacturing',
    'summary': '模切管理系统',
    'depends': ['base', 'product', 'sale', 'purchase', 'stock', 'website', 'website_sale', 'mail', 'web_hierarchy'],
    "data": [
        "data/ir_sequence_data.xml",
        "data/mail_template_data.xml",
        "data/sequence.xml",
        "data/product_category_data.xml",
        "data/catalog_sidike_dst_data.xml",
        "data/catalog_sidike_uv_data.xml",
        "data/catalog_tesa_acrylic_foam_data.xml",
        "security/ir.model.access.csv",
        
        "views/my_material_base_views.xml",
        "report/diecut_mold_reports.xml",
        "views/diecut_quote_views.xml",
        "views/requisition_views.xml",
        "views/slitting_views.xml",
        "views/mold_views.xml",
        "views/mold_search_view.xml",
        "views/mold_location_views.xml",
        "views/mold_scrap_wizard_view.xml",
        "views/mold_qc_wizard_view.xml",
        "views/purchase_order_inherit_view.xml",
        "views/stock_quant_views.xml",

        "views/res_partner_view.xml",
        "views/sale_order_inherit_view.xml",
        "views/sample_order_view.xml",
        "views/website_templates.xml",
        "views/product_category_view.xml",
        "views/material_catalog_views.xml",
        "wizard/catalog_activate_wizard_view.xml",
        "views/diecut_menu_view.xml"
    ],
    'assets': {
        'web.assets_backend': [
            'diecut/static/src/scss/custom_font.scss',
            'diecut/static/src/scss/hierarchy_view.scss',
            'diecut/static/src/scss/list_view_hover.scss',
            'diecut/static/src/js/enter_to_next.js',
            'diecut/static/src/js/shift_select.js',
            'diecut/static/src/js/catalog_dynamic_columns.js',
            'diecut/static/src/scss/quick_entry.scss',
            'diecut/static/src/xml/search_panel_inherit.xml',
        ],
    },
    'external_dependencies': {
        'python': ['qrcode'],
    },
    'installable': True,
    'application': True,
}
