# -*- coding: utf-8 -*-
{
    'name': '模切管理系统',
    'version': '1.0',
    'category': 'Manufacturing',
    'summary': '模切管理系统',
    'author': 'Diecut Team',
    'license': 'LGPL-3',
    'depends': ['base', 'product', 'sale', 'purchase', 'stock', 'mail', 'web_hierarchy'],
    "data": [
        "data/ir_sequence_data.xml",
        "data/mail_template_data.xml",
        "data/sequence.xml",
        "data/product_category_data.xml",
        "data/catalog_spec_def_data.xml",
        "security/ir.model.access.csv",
        "data/catalog_item_spec_migration.xml",
        
        "views/my_material_base_views.xml",
        "report/diecut_mold_reports.xml",
        "views/diecut_quote_views.xml",
        "views/requisition_views.xml",
        "views/slitting_views.xml",
        "views/mold_views.xml",
        "views/mold_search_view.xml",
        "views/mold_location_views.xml",
        "views/mold_scrap_wizard_view.xml",
        "views/mold_qc_wizard_view.xml",
        "views/purchase_order_inherit_view.xml",
        "views/stock_quant_views.xml",

        "views/res_partner_view.xml",
        "views/sale_order_inherit_view.xml",
        "views/sample_order_view.xml",
        "views/product_category_view.xml",
        "views/catalog_spec_views.xml",
        "views/catalog_series_views.xml",
        "views/catalog_item_views.xml",
        "views/diecut_brand_views.xml",
        "wizard/catalog_activate_wizard_view.xml",
        "wizard/catalog_series_apply_wizard_view.xml",
        "wizard/catalog_item_batch_update_wizard_view.xml",
        "wizard/catalog_ops_wizard_view.xml",
        "views/diecut_menu_view.xml"
    ],
    'assets': {
        'web.assets_backend': [
            'diecut/static/src/scss/custom_font.scss',
            'diecut/static/src/scss/hierarchy_view.scss',
            'diecut/static/src/scss/list_view_hover.scss',
            'diecut/static/src/js/enter_to_next.js',
            'diecut/static/src/js/shift_select.js',
            'diecut/static/src/js/catalog_dynamic_columns.js',
            'diecut/static/src/js/material_split_preview.js',
            'diecut/static/src/js/spec_value_field.js',
            'diecut/static/src/scss/quick_entry.scss',
            'diecut/static/src/scss/material_split_preview.scss',
            'diecut/static/src/xml/search_panel_inherit.xml',
            'diecut/static/src/xml/material_split_preview.xml',
            'diecut/static/src/xml/spec_value_field.xml',
        ],
    },
    'external_dependencies': {
        'python': ['qrcode'],
    },
    'installable': True,
    'application': True,
    # 'post_init_hook': 'odoo.addons.diecut.scripts.migrate_thickness_std_um_to_unicode.post_init_hook',
}
